version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: [GEOTASK_GRAFANA]/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana:/var/lib/grafana

  geo-service:
    build:
      context: .cmd/api
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
